name: tagEat
description: A food inventory management system.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  water_drop_nav_bar: ^2.1.0+8
  battery_indicator: ^0.1.1
  percent_indicator: ^4.0.0
  pandabar: ^0.1.2
  flutter_snake_navigationbar: ^0.6.1
  qr_code_scanner: ^0.7.0
  flutter_number_picker: ^1.0.4
  horizontal_picker: ^1.2.0
  group_radio_button: ^1.2.0
  http: ^0.13.4
  url_launcher: ^6.0.20
  web_socket_channel: ^2.1.0
  dropdown_button2: ^1.2.2
  toggle_switch: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: muli
      fonts:
        - asset: assets/fonts/muli.ttf